### PR TITLE
workshop: Adding Lambda functions in Python

### PR DESCRIPTION
**Pull request by leandrodamascena**
**Description of changes:**

In this PR I am adding Lambda functions (Python version) for the OPN301 workshop

What is still missing in this PR:
- [x] Module 1 - Missing some pieces
- [ ] Module 2 - Fixing bugs locally before send the commit
- [x] Module 3 - Should have more details?  

I'll create this PR in draft mode and probably tomorrow I'll convert to Ready for Review. Please don't merge until then.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by dreamorosi** [comment]
After merging #14 I have added the conditional logic to deploy the modules in each language by running `LANGUAGE=nodejs npm run infra:deploy` (see contributing doc for possible values).

Please rebase `main` and incorporate your proposed functions in the `if/else` statement for the appropriate language.

**Comment by leandrodamascena** [comment]
Hey @dreamorosi! Ok ok, I'll incorporate my functions and add my constructors here:

```typescript
} else if (language === 'python') {
      throw new Error('Python not implemented yet');
```

I fixed all the bugs in module 1 and I'm fixing the bugs in module 2. Should we worry about comments at this point? I see that I need to add a lot of comments to my functions to explain what is happening.

**Comment by dreamorosi** [comment]
No need for now, we can do the comments later

**Comment by leandrodamascena** [comment]
Update

- [x] Module 1 - OK
- [ ] Module 2 - Missing API CALL
- [x] Module 3 - OK

**Comment by leandrodamascena** [comment]
Python functions and builds have been included in the CDK.

**Comment by leandrodamascena** [comment]
Update

- [x] Module 1 - OK
- [x] Module 2 - OK
- [x] Module 3 - OK


Hey @dreamorosi, you can merge this PR :)

**Comment by dreamorosi** [comment]
Thank you Leo, I'll merge tonight

**Comment by leandrodamascena** [comment]
Hey Andrea. Let me improve just a few parts of the code and we'll merge it tonight. I'll let you know

**Review by dreamorosi — APPROVED** [review]
Thanks Leo!

**Pull request merged**
